server:
  port: 8080

spring:
  application:
    name: product-service
  profiles:
    active: default
  cloud:
    config:
        enabled: true
        uri: http://localhost:8888
  config:
    import: configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka